/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editorQuestoes;

import banco.Questoes;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Couth
 */
public class AdicionarImagem extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarImagem
     */
    boolean adicionou = false;
    Questoes questoesBanco = new Questoes();
    ResultSet rs;
    int posicao;
    String nome;   
    Blob img;
    public AdicionarImagem() {
        initComponents();
        setLocationRelativeTo(null);        
    }
    
    public AdicionarImagem(String nome) {
        initComponents();
        setLocationRelativeTo(null); 
        nome = this.nome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbEsquerda = new javax.swing.JRadioButton();
        jrbCentralizada = new javax.swing.JRadioButton();
        jrbDireita = new javax.swing.JRadioButton();
        jbSalvar = new javax.swing.JButton();
        jbCarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecione a posição da imagem em relação ao texto:");

        buttonGroup1.add(jrbEsquerda);
        jrbEsquerda.setText("Esquerda");

        buttonGroup1.add(jrbCentralizada);
        jrbCentralizada.setText("Centralizada");

        buttonGroup1.add(jrbDireita);
        jrbDireita.setText("Direita");

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCarregar.setText("Carregar imagem");
        jbCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jbCarregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jrbEsquerda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbCentralizada)
                        .addGap(31, 31, 31)
                        .addComponent(jrbDireita)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbEsquerda)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbDireita)
                        .addComponent(jrbCentralizada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCarregar)
                    .addComponent(jbSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        //CONFERIR
        if ((jrbEsquerda.isSelected())||(jrbCentralizada.isSelected())||(jrbDireita.isSelected())) {           
            if (jrbEsquerda.isSelected()) {
                posicao = 1;
            }
            if (jrbCentralizada.isSelected()) {
                posicao = 2;
            }
            if (jrbDireita.isSelected()) {
                posicao = 3;
            }
            try {
                rs = questoesBanco.pegarConteudosID(nome);                
                if (rs!=null) {                    
                    //img está vazio                    
                    questoesBanco.inserirImagem(rs.getInt("Conteudos_ID"), img, posicao);
                    dispose();
                }
            } catch (SQLException ex) {
                //Error msg
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione a posição da imagem!");
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarActionPerformed
        // TODO add your handling code here:     
        //passar valor da busca pro img aqui
        //passar para a img o valor da busca do método
        buscar();
        if (adicionou)
            jbSalvar.setEnabled(true);
    }//GEN-LAST:event_jbCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarImagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarImagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarImagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarImagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarImagem().setVisible(true);
            }
        });
    }
    
    public void buscar() {
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter(
                "Imagens", "png", "jpg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(fileNameExtensionFilter);
        chooser.setDialogTitle("Selecione a imagem");
        int resposta = chooser.showOpenDialog(null);
        if (resposta == JFileChooser.APPROVE_OPTION) {
            File file = new File(chooser.getSelectedFile().getAbsolutePath());
            FileReader fis;
            try {
                fis = new FileReader(file);
                BufferedReader bis = new BufferedReader(fis);
                while (bis.ready()) {
                    System.out.println(bis.readLine()+"\n");
                }
                bis.close();
                fis.close();
                adicionou = true;
            } catch (FileNotFoundException e) {
                adicionou = false;
            } catch (IOException e) {
                adicionou = false;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCarregar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JRadioButton jrbCentralizada;
    private javax.swing.JRadioButton jrbDireita;
    private javax.swing.JRadioButton jrbEsquerda;
    // End of variables declaration//GEN-END:variables
}
