/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package editorQuestoes;

import banco.Questoes;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import telas.MenuGUI;

/**
 *
 * @author Couth
 */
public class TelaDeQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeQuestoes
     */
    DefaultTableModel modelTabela;
    ResultSet rs;
    Questoes questoes = new Questoes();
    public TelaDeQuestoes() {
        initComponents();
        setLocationRelativeTo(null);
        
        //TABELA QUESTÕES
        modelTabela = new DefaultTableModel();
        tabelaQuestoes.setModel(modelTabela);
        modelTabela.addColumn("Id");
        modelTabela.addColumn("Enunciado");
        modelTabela.addColumn("Dificuldade");
        modelTabela.addColumn("Tipo de questão");        
        //modelTabela.addColumn("Alternativa A");
        //modelTabela.addColumn("Alternativa B");
        //modelTabela.addColumn("Alternativa C");
        //modelTabela.addColumn("Alternativa D");
        //modelTabela.addColumn("Alternativa E");
        //modelTabela.addColumn("Alternativa F");
        
        try {
            rs = questoes.pegarQuestao();
            if (rs!=null) {
                do {
                    modelTabela.addRow(new Object[]{                        
                        rs.getString("Questoes_ID"),
                        rs.getString("Enunciado"),
                        rs.getString("Dificuldade"),
                        rs.getString("MultiplaEscolha"),
                    });
                } while (rs.next());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
        
        tabelaQuestoes.getColumnModel().getColumn(0).setMinWidth(40);
        tabelaQuestoes.getColumnModel().getColumn(2).setMinWidth(75);
        tabelaQuestoes.getColumnModel().getColumn(3).setMinWidth(100);
        
        tabelaQuestoes.getColumnModel().getColumn(0).setMaxWidth(40);
        tabelaQuestoes.getColumnModel().getColumn(2).setMaxWidth(75);
        tabelaQuestoes.getColumnModel().getColumn(3).setMaxWidth(100);  
        
        tabelaQuestoes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jmiEditar.setEnabled(true);
                jmiExcluir.setEnabled(true);
            }
        });
        
        jtPesquisar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                jbPesquisarActionPerformed(null);                
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (jtPesquisar.getText().isEmpty()) {
                    jbVerTodasActionPerformed(null);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //
            }
        });        
        
        for (int i=0; i<=(tabelaQuestoes.getRowCount()-1); i++) {
            String multipla = tabelaQuestoes.getModel().getValueAt(i, 3).toString();
            if (multipla.equals("N")) {
                tabelaQuestoes.getModel().setValueAt("Aberta", i, 3);
            }
            if (multipla.equals("S")) {
                tabelaQuestoes.getModel().setValueAt("Fechada", i, 3);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaQuestoes = new javax.swing.JTable();
        jtPesquisar = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jlQuestoesPesquisadas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbVerTodas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiEditar = new javax.swing.JMenuItem();
        jmiExcluir = new javax.swing.JMenuItem();
        jmiPesquisar = new javax.swing.JMenuItem();
        jmiVerTodas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaQuestoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaQuestoes);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlQuestoesPesquisadas.setText("Todas as questões cadastradas:");

        jLabel2.setText("Pesquisar questão:");

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbVerTodas.setText("Ver todas questões");
        jbVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQuestoesPesquisadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbVerTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditar)
                        .addComponent(jbExcluir)
                        .addComponent(jbVerTodas))
                    .addComponent(jlQuestoesPesquisadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setText("Adicionar questão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmiSair.setText("Menu principal");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Questões");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmiEditar.setText("Editar");
        jmiEditar.setEnabled(false);
        jMenu2.add(jmiEditar);

        jmiExcluir.setText("Excluir");
        jmiExcluir.setEnabled(false);
        jMenu2.add(jmiExcluir);

        jmiPesquisar.setText("Pesquisar");
        jmiPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPesquisar);

        jmiVerTodas.setText("Ver todas");
        jmiVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVerTodasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiVerTodas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here: 
        String enunciado = jtPesquisar.getText();
        if (!enunciado.isEmpty()) {
            try {
                for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                    modelTabela.removeRow(i);
                }            
                rs = questoes.pesquisarQuestao(enunciado);
                if (rs!=null) {                
                    do {
                        modelTabela.addRow(new Object[]{
                            rs.getString("Questoes_ID"),
                            rs.getString("Enunciado"),
                            rs.getString("Dificuldade"),
                            rs.getString("MultiplaEscolha"),
                        });
                    } while (rs.next());
                    tabelaQuestoes.setModel(modelTabela);
                }
                
                jlQuestoesPesquisadas.setText("Você pesquisou por: "+enunciado);                                                    

                for (int i=0; i<=(tabelaQuestoes.getRowCount()-1); i++) {
                    String multipla = tabelaQuestoes.getModel().getValueAt(i, 3).toString();
                    if (multipla.equals("N")) {
                        tabelaQuestoes.getModel().setValueAt("Aberta", i, 3);
                    }
                    if (multipla.equals("S")) {
                        tabelaQuestoes.getModel().setValueAt("Fechada", i, 3);
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você não digitou nada no campo de pesquisa!");
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerTodasActionPerformed
        // TODO add your handling code here:
        try {
            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }
            rs = questoes.pegarQuestao();
            if (rs!=null) {                
                do {
                    modelTabela.addRow(new Object[]{
                        rs.getString("Questoes_ID"),
                        rs.getString("Enunciado"),
                        rs.getString("Dificuldade"),
                        rs.getString("MultiplaEscolha"),
                    });
                } while (rs.next());
                tabelaQuestoes.setModel(modelTabela);
            }
            jlQuestoesPesquisadas.setText("Todas as questões cadastradas:");    
            jtPesquisar.setText("");
            jtPesquisar.requestFocus();
            
            for (int i=0; i<=(tabelaQuestoes.getRowCount()-1); i++) {
                String multipla = tabelaQuestoes.getModel().getValueAt(i, 3).toString();
                if (multipla.equals("N")) {
                    tabelaQuestoes.getModel().setValueAt("Aberta", i, 3);
                }
                if (multipla.equals("S")) {
                    tabelaQuestoes.getModel().setValueAt("Fechada", i, 3);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
    }//GEN-LAST:event_jbVerTodasActionPerformed
    
    private void jmiPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPesquisarActionPerformed
        // TODO add your handling code here:
        jbPesquisarActionPerformed(evt);
    }//GEN-LAST:event_jmiPesquisarActionPerformed

    private void jmiVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVerTodasActionPerformed
        // TODO add your handling code here:
        jbVerTodasActionPerformed(evt);
    }//GEN-LAST:event_jmiVerTodasActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int row = tabelaQuestoes.getSelectedRow();
        int numero = tabelaQuestoes.getSelectedRowCount();
        if (numero == 1) {           
            String multipla = tabelaQuestoes.getModel().getValueAt(row, 3).toString();        
            int id = Integer.parseInt(tabelaQuestoes.getModel().getValueAt(row, 0).toString());
            
            if (multipla.equals("Aberta")) {
                EditorQuestaoAberta editor = new EditorQuestaoAberta(this, true, id);
                editor.setVisible(true);                      
            }
            
            if (multipla.equals("Fechada")) {
                EditorQuestaoFechada editor = new EditorQuestaoFechada(this, true, id);
                editor.setVisible(true);                      
            }
            
            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }   
            
            try {
                rs = questoes.pegarQuestao();
                if (rs!=null) {
                    do {
                        modelTabela.addRow(new Object[]{                        
                            rs.getString("Questoes_ID"),
                            rs.getString("Enunciado"),
                            rs.getString("Dificuldade"),
                            rs.getString("MultiplaEscolha"),
                        });
                    } while (rs.next());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }
            
            for (int i=0; i<=(tabelaQuestoes.getRowCount()-1); i++) {
                multipla = tabelaQuestoes.getModel().getValueAt(i, 3).toString();
                if (multipla.equals("N")) {
                    tabelaQuestoes.getModel().setValueAt("Aberta", i, 3);
                }
                if (multipla.equals("S")) {
                    tabelaQuestoes.getModel().setValueAt("Fechada", i, 3);
                }
            }
            
            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jmiEditar.setEnabled(false);
            jmiExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:        
        int numero = tabelaQuestoes.getSelectedRowCount();
        String mensagem;               
        if (numero == 1) {
            mensagem = "Tem certeza que deseja excluir esta questão?";
        } else { 
            mensagem = "Tem certeza que deseja excluir "+numero+" questões?";
        }
        
        int[] row = tabelaQuestoes.getSelectedRows();
        int x = JOptionPane.showConfirmDialog(this.getContentPane(), mensagem, "Excluir dados", 
                JOptionPane.YES_NO_CANCEL_OPTION);
        if (x==0) {          
            for (int i=0; i<numero; i++) {
                try {
                    int id = Integer.parseInt(tabelaQuestoes.getModel().getValueAt(row[i], 0).toString());
                    questoes.excluirQuestaoPeloId(id);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao excluir.\nErro: "+ex);
                }
            }            
            
            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }   
            
            try {
                rs = questoes.pegarQuestao();
                if (rs!=null) {
                    do {
                        modelTabela.addRow(new Object[]{                        
                            rs.getString("Questoes_ID"),
                            rs.getString("Enunciado"),
                            rs.getString("Dificuldade"),
                            rs.getString("MultiplaEscolha"),
                        });
                    } while (rs.next());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }
            
            for (int i=0; i<=(tabelaQuestoes.getRowCount()-1); i++) {
                String multipla = tabelaQuestoes.getModel().getValueAt(i, 3).toString();
                if (multipla.equals("N")) {
                    tabelaQuestoes.getModel().setValueAt("Aberta", i, 3);
                }
                if (multipla.equals("S")) {
                    tabelaQuestoes.getModel().setValueAt("Fechada", i, 3);
                }
            }
            
            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jmiEditar.setEnabled(false);
            jmiExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        MenuGUI menu = new MenuGUI();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        EditorDeQuestoes editor = new EditorDeQuestoes();
        editor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeQuestoes().setVisible(true);
            }
        });
    } 
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbVerTodas;
    private javax.swing.JLabel jlQuestoesPesquisadas;
    private javax.swing.JMenuItem jmiEditar;
    private javax.swing.JMenuItem jmiExcluir;
    private javax.swing.JMenuItem jmiPesquisar;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiVerTodas;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTable tabelaQuestoes;
    // End of variables declaration//GEN-END:variables
}
