/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import banco.Cabecalho;
/**
 *
 * @author Couth
 */
public class TelaDeCabecalhosGUI extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCabecalhosGUI
     */
    DefaultTableModel modelTabela;
    ResultSet rs;
    Cabecalho cabecalho = new Cabecalho();
    public TelaDeCabecalhosGUI() {
        initComponents();
        setLocationRelativeTo(null);
        
        //TABELA QUESTÕES
        modelTabela = new DefaultTableModel();
        tabelaCabecalhos.setModel(modelTabela);
        modelTabela.addColumn("Id");
        modelTabela.addColumn("Nome da Instituição");
        modelTabela.addColumn("Título");
        modelTabela.addColumn("Série");
        modelTabela.addColumn("Valor");        
        
        try {
            rs = cabecalho.pegarCabecalho();
            if (rs!=null) {
                do {
                    modelTabela.addRow(new Object[]{                        
                        rs.getString("Cabecalho_ID"),
                        rs.getString("NomeInstituicao"),
                        rs.getString("Titulo"),
                        rs.getString("Serie"),
                        rs.getString("Valor"),
                    });
                } while (rs.next());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
        
        tabelaCabecalhos.getColumnModel().getColumn(0).setMinWidth(40);
        tabelaCabecalhos.getColumnModel().getColumn(1).setMinWidth(175);
        tabelaCabecalhos.getColumnModel().getColumn(2).setMinWidth(125);
        tabelaCabecalhos.getColumnModel().getColumn(3).setMinWidth(75);
        tabelaCabecalhos.getColumnModel().getColumn(4).setMinWidth(100);
        
        tabelaCabecalhos.getColumnModel().getColumn(0).setMaxWidth(40);
        tabelaCabecalhos.getColumnModel().getColumn(3).setMaxWidth(75);
        tabelaCabecalhos.getColumnModel().getColumn(4).setMaxWidth(100);  
        
        tabelaCabecalhos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jmiEditar.setEnabled(true);
                jmiExcluir.setEnabled(true);
            }
        });
        
        jtPesquisar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                jbPesquisarActionPerformed(null);                
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (jtPesquisar.getText().isEmpty()) {
                    jbVerTodasActionPerformed(null);
                } else {
                    jbPesquisarActionPerformed(null);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //
            }
        });                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCabecalhos = new javax.swing.JTable();
        jtPesquisar = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jlCabecalhosPesquisadas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbVerTodas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiEditar = new javax.swing.JMenuItem();
        jmiExcluir = new javax.swing.JMenuItem();
        jmiPesquisar = new javax.swing.JMenuItem();
        jmiVerTodas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaCabecalhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaCabecalhos);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlCabecalhosPesquisadas.setText("Todas os cabeçalhos cadastrados:");

        jLabel2.setText("Pesquisar cabeçalho:");

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbVerTodas.setText("Ver todos cabeçalhos");
        jbVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlCabecalhosPesquisadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbVerTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditar)
                        .addComponent(jbExcluir)
                        .addComponent(jbVerTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlCabecalhosPesquisadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setText("Adicionar cabeçalho");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmiSair.setText("Menu principal");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cabeçalho");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jmiEditar.setText("Editar");
        jmiEditar.setEnabled(false);
        jmiEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiEditar);

        jmiExcluir.setText("Excluir");
        jmiExcluir.setEnabled(false);
        jmiExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExcluirActionPerformed(evt);
            }
        });
        jMenu2.add(jmiExcluir);

        jmiPesquisar.setText("Pesquisar");
        jmiPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPesquisar);

        jmiVerTodas.setText("Ver todas");
        jmiVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVerTodasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiVerTodas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:
        String enunciado = jtPesquisar.getText();
        if (!enunciado.isEmpty()) {
            try {                
                for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                    modelTabela.removeRow(i);
                }
                rs = cabecalho.pesquisarCabecalho(enunciado);                
                if (rs!=null) {
                    do {
                        modelTabela.addRow(new Object[]{
                            rs.getString("Cabecalho_ID"),
                            rs.getString("NomeInstituicao"),
                            rs.getString("Titulo"),
                            rs.getString("Serie"),
                            rs.getString("Valor"),
                        });
                    } while (rs.next());
                    tabelaCabecalhos.setModel(modelTabela);
                }

                jlCabecalhosPesquisadas.setText("Você pesquisou por: "+enunciado);                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você não digitou nada no campo de pesquisa!");
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int row = tabelaCabecalhos.getSelectedRow();
        int numero = tabelaCabecalhos.getSelectedRowCount();
        if (numero == 1) {
            int id = Integer.parseInt(tabelaCabecalhos.getModel().getValueAt(row, 0).toString());
            
            EditorCabecalhoGUI editor = new EditorCabecalhoGUI(this, true, id);
            editor.setVisible(true);
            
            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }
            
            try {
                rs = cabecalho.pegarCabecalho();
                if (rs!=null) {
                    do {
                        modelTabela.addRow(new Object[]{
                            rs.getString("Cabecalho_ID"),
                            rs.getString("NomeInstituicao"),
                            rs.getString("Titulo"),
                            rs.getString("Serie"),
                            rs.getString("Valor"),
                        });
                    } while (rs.next());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }

            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jmiEditar.setEnabled(false);
            jmiExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        int numero = tabelaCabecalhos.getSelectedRowCount();
        String mensagem;
        if (numero == 1) {
            mensagem = "Tem certeza que deseja excluir este cabeçalho?";
        } else {
            mensagem = "Tem certeza que deseja excluir "+numero+" cabeçalhos?";
        }

        int[] row = tabelaCabecalhos.getSelectedRows();
        int x = JOptionPane.showConfirmDialog(this.getContentPane(), mensagem, "Excluir dados",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if (x==0) {
            for (int i=0; i<numero; i++) {
                try {
                    int id = Integer.parseInt(tabelaCabecalhos.getModel().getValueAt(row[i], 0).toString());
                    cabecalho.excluirCabecalhoPeloId(id);
                    if ((i==0)&&((i+1)==numero)) {
                        JOptionPane.showMessageDialog(this, "Cabeçalho excluido com sucesso!");
                    } else if ((i+1)==numero) {
                        JOptionPane.showMessageDialog(this, "Cabeçalhos excluidos com sucesso!");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao excluir.\nErro: "+ex);
                }
            }

            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }

            try {
                rs = cabecalho.pegarCabecalho();
                if (rs!=null) {
                    do {
                        modelTabela.addRow(new Object[]{
                            rs.getString("Cabecalho_ID"),
                            rs.getString("NomeInstituicao"),
                            rs.getString("Titulo"),
                            rs.getString("Serie"),
                            rs.getString("Valor"),
                        });
                    } while (rs.next());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
            }

            jbEditar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jmiEditar.setEnabled(false);
            jmiExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        CabecalhoGUI editor = new CabecalhoGUI();
        editor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        MenuGUI menu = new MenuGUI();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPesquisarActionPerformed
        // TODO add your handling code here:
        jbPesquisarActionPerformed(evt);
    }//GEN-LAST:event_jmiPesquisarActionPerformed

    private void jbVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerTodasActionPerformed
        // TODO add your handling code here:
        try {
            for (int i=(modelTabela.getRowCount()-1); i>=0; i--) {
                modelTabela.removeRow(i);
            }
            rs = cabecalho.pegarCabecalho();
            if (rs!=null) {
                do {
                    modelTabela.addRow(new Object[]{
                        rs.getString("Cabecalho_ID"),
                        rs.getString("NomeInstituicao"),
                        rs.getString("Titulo"),
                        rs.getString("Serie"),
                        rs.getString("Valor"),
                    });
                } while (rs.next());
                tabelaCabecalhos.setModel(modelTabela);
            }
            jlCabecalhosPesquisadas.setText("Todas os cabeçalhos cadastrados:");
            jtPesquisar.setText("");
            jtPesquisar.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage());
        }
    }//GEN-LAST:event_jbVerTodasActionPerformed

    private void jmiVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVerTodasActionPerformed
        // TODO add your handling code here:
        jbVerTodasActionPerformed(evt);
    }//GEN-LAST:event_jmiVerTodasActionPerformed

    private void jmiEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarActionPerformed
        // TODO add your handling code here:
        jbEditarActionPerformed(evt);
    }//GEN-LAST:event_jmiEditarActionPerformed

    private void jmiExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExcluirActionPerformed
        // TODO add your handling code here:
        jbExcluirActionPerformed(evt);
    }//GEN-LAST:event_jmiExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCabecalhosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCabecalhosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCabecalhosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCabecalhosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCabecalhosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbVerTodas;
    private javax.swing.JLabel jlCabecalhosPesquisadas;
    private javax.swing.JMenuItem jmiEditar;
    private javax.swing.JMenuItem jmiExcluir;
    private javax.swing.JMenuItem jmiPesquisar;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiVerTodas;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTable tabelaCabecalhos;
    // End of variables declaration//GEN-END:variables
}
